name: Build Docs

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-get-deps==0.2.0 mkdocs-glightbox==0.4.0 mkdocs-material==9.6.12 mkdocs-material-extensions==1.3.1
      - name: Build Docs
        run: cd docs && mkdocs build
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/site/
          # This will not fail if there are no changes
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated site content via GitHub Actions"
          git push
